# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fe8afa8e52f5db258b464f7a45f424b4"
application_url = "https://guru-civic-terrain-perry.trycloudflare.com"
embedded = true
name = "wish-it"
handle = "wish-it"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://guru-civic-terrain-perry.trycloudflare.com/auth/callback",
  "https://guru-civic-terrain-perry.trycloudflare.com/auth/shopify/callback",
  "https://guru-civic-terrain-perry.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
